### ISSUE TITLE
vm_setup not Mac friendly

### ISSUE THREAD

**Issue by JPerkster** [cPanelTechs/vm_setup#10]
• [Perk@Perks-Mac:~/projects/vm_setup] (master)# perl vm_setup.pl 
    Possible unintended interpolation of @55 in string at vm_setup.pl line 185.
    
    VM Server Setup Script
    Version: 0.3.1

    creating lock file
    touch: /root/vmsetup.lock: No such file or directory
    installing utilities via yum [mtr nmap telnet nc jq s3cmd bind-utils jwhois dev git]
    Can't exec "yum": No such file or directory at vm_setup.pl line 294.
    readline() on closed filehandle $cmd at vm_setup.pl line 295.
    setting hostname
    hostname: sethostname: Operation not permitted
        Permission denied
    Died at vm_setup.pl line 92.

**Comment by cPanelPeter** [comment]
This is designed only to work on our Meteorologist/Horizon VM (openstack) servers.  Not Mac's.  
The issue is that once a VM is built it take a while to get it to a functioning state because of all the additional set up that has to happen.  This script was designed to make that task easier and faster because when trying to replicate bugs and there are a lot of tickets, then time is of the essence.

I cannot duplicate the errors you're seeing on CentOS VM's.  So I will add an OS check to this script.

Thanks
